# Generated by Django 4.2.23 on 2025-06-27 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='企業名')),
                ('job_title', models.CharField(max_length=255, verbose_name='応募職種')),
                ('status', models.CharField(choices=[('検討中', '応募検討中'), ('応募済', '書類応募済'), ('選考中', '選考中'), ('内定', '内定'), ('見送り', '見送り')], default='検討中', max_length=20, verbose_name='選考ステージ')),
                ('next_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='次のアクション')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='次のアクションの日付')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='求人情報(AI用)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='書類名（例：職務経歴書_v2）')),
                ('uploaded_file', models.FileField(upload_to='documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobinfo_application.jobapplication')),
            ],
        ),
    ]
