# Generated by Django 4.2.23 on 2025-06-30 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobinfo_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='ここに求人情報をコピー＆ペーストすると、AIによる志望動機作成支援機能が利用できます。', null=True, verbose_name='求人情報'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='next_action',
            field=models.CharField(blank=True, help_text='例：面接日程の調整メール返信, Webテスト受験など', max_length=255, null=True, verbose_name='次のタスク'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='next_action_date',
            field=models.DateField(blank=True, help_text='面接の日付や、タスクの締切日などを入力します。', null=True, verbose_name='タスクの期日/予定日'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, help_text='プログラミング言語、フレームワーク、保有資格などを自由にご記入ください。', verbose_name='スキル・資格')),
                ('experience', models.TextField(blank=True, help_text='これまでであなたが注力したことなどを具体的に記述してください。', verbose_name='職務経歴・学業経験')),
                ('self_pr', models.TextField(blank=True, help_text='あなたの強みや、仕事に対する価値観などを自由にご記入ください。', verbose_name='自己PR')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
