# Generated by Django 4.2.23 on 2025-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobinfo_application', '0002_alter_jobapplication_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='corporate_philosophy',
            field=models.TextField(blank=True, help_text='企業の公式サイトに記載の経営理念・ビジョンをコピー＆ペーストしてください。', null=True, verbose_name='経営理念・ビジョン'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ideal_candidate',
            field=models.TextField(blank=True, help_text='企業の採用ページなどに記載の「求める人物像」をコピー＆ペーストしてください。', null=True, verbose_name='企業の求める人物像'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='書類名（例：エントリーシート_v1など）'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='企業の業務内容をコピー＆ペーストしてください。', null=True, verbose_name='業務内容'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='next_action',
            field=models.CharField(blank=True, help_text='例：面接,グループディスカッション、Webテスト受験など', max_length=255, null=True, verbose_name='次のタスク'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='next_action_date',
            field=models.DateField(blank=True, help_text='面接の日付や、提出物の締切日などを入力します。', null=True, verbose_name='タスクの期日/予定日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='これまでであなたが注力したことを具体的に記入してください。', verbose_name='職務経歴・学業経験'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='self_pr',
            field=models.TextField(blank=True, help_text='あなたの強みや、仕事に対する価値観を記入してください。', verbose_name='自己PR'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='プログラミング言語、フレームワーク、保有資格など記入してください。', verbose_name='スキル・資格'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_types',
            field=models.ManyToManyField(blank=True, to='jobinfo_application.jobtype', verbose_name='職種カテゴリ'),
        ),
    ]
